server:
  port: 80


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: sqlRoot@123
    url: jdbc:mariadb://10.100.201.33:3306/db_exodia?characterEncoding=UTF-8&useSSL=false&serverTimeZone=UTC

---

logging:
  level:
    com.hichaoren: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
